### ISSUE TITLE
Exporting mesh and sif

### ISSUE THREAD

**Issue by HoWilgh** [physici/ElmerSalome#21]
Hello,
I tested your script and got the two following messages when trying to:

-export the mesh
![screenshot from 2017-03-20 15-18-07](https://cloud.githubusercontent.com/assets/9978035/24104266/0f0c76b4-0d82-11e7-8b02-81dd2b2ccde3.png)
BTW: .unv is not automatically added when exporting the mesh.

-write the .sif
![screenshot from 2017-03-20 15-18-45](https://cloud.githubusercontent.com/assets/9978035/24104306/2e0f21f6-0d82-11e7-896d-b7d30eda0472.png)

if necessary ... here is the zipped demo project:
[Study1_example.hdf.zip](https://github.com/physici/ElmerSalomeModule/files/855266/Study1_example.hdf.zip)

Hope this is helpful,
Thanks for developing this plugin,
HoWil

**Comment by physici** [comment]
Thanks for testing.
I have fixed the mesh-creation error. Should work now. However, at my machine the '.unv'-ending is added automatically. Are you running Linux?

**Comment by HoWilgh** [comment]
Many thanks, 
I run ubuntu linux 1604. And will test it again. 
BR, 
Howil

**Comment by physici** [comment]
I have updated the sif-writer functionality and tested it on my machine with Salome 7.8. It creates the file as intended, but I have not checked if Elmer would run correctly (no time at the moment).

**Comment by physici** [comment]
I have updated the sif-writer class. It works with my Salome 7.8 installation and creates a sif-file the Elmer runs without an error. The mesh export works as well. Have not checked the correctness of the result yet. But it might be a  starting point for you.

**Comment by HoWilgh** [comment]
After fresh pull I still get the following error when trying to export the mesh.
![screenshot from 2017-03-27 21-30-19](https://cloud.githubusercontent.com/assets/9978035/24374596/bfd0ff52-1335-11e7-97fa-5eafaa965cb4.jpg)

Mesh is only exported as export.unv when inserting the complete name "export.unv". Otherwise I get a "export" file without ending.  

The .sif export works fine but could not test if a working simulation can be built.
BR,
HoWil

**Comment by physici** [comment]
Okay, thanks for the update. It is obviously a Linux-thing. I will make a modification to the export function.

**Comment by physici** [comment]
I have uploaded a new version. You might want to try that one.

**Comment by HoWilgh** [comment]
I just cloned the repository and get all files doubled. Most of them are inside the ElmerSalome folder and next to it!

Additionally, the plugin is no more visible in the menu under Tools->Plugins

Did something change regarding the folder- and  filenaming?
BR,
HoWil

**Comment by physici** [comment]
Hi, 
I am very sorry. I used the web application to upload the files resulting in a big mess.

I have corrrected the file structure. I also tested a clone of the current repository with Salome 7.8 and Salome 8.2 on Windows. Both things work.

If the Plugin does not appear in Tools anymore, please check the console output if there is an error notification there. Could you copy that one?

Regards,
Rainer

**Comment by HoWilgh** [comment]
> I am very sorry. 
No problems.... its great that you write this plugin.

I still get the following error when exporting the mesh. Nevertheless, the mesh seems fine.
.sif export works again fine.

Would it be possible to run ElmerGrid also, maybe as an option when exporting the mesh.

BR
HoWil
![screenshot from 2017-03-28 15-54-08](https://cloud.githubusercontent.com/assets/9978035/24409001/5d2f36ee-13cf-11e7-89ab-020bef371291.jpg)

**Comment by physici** [comment]
Could you check, if the .unv-file exists in the directory after export? Additionally, I have modified the salome_plugins.py to get some additional information. Please replace your local copy. Maybe we can find out what is going wrong on your end.

**Comment by HoWilgh** [comment]
Made a clean clone and got the following message; the unv is exported without problems:
![screenshot from 2017-03-29 15-32-43](https://cloud.githubusercontent.com/assets/9978035/24457121/88d0229c-1495-11e7-8fed-203642059d94.jpg)

**Comment by physici** [comment]
Hmm.. Sorry, again. It seems that my Qt behaves a bit different - reason unknown. I have made a small alteration to the code, using a different kind of messagebox. Could you try it again.
If it still does not work, please remove line 306 from the salome_plugins.py-file manually [(see here)](https://github.com/physici/ElmerSalomeModule/blob/master/salome_plugins.py#L306) and try again.

I just need the information that is stored in the variables 'fname' and 'path'.  I assume that your problem is related to the way file names are handled/formated on Linux.

If you have the strings that are stored in 'fname' and 'path', could you go the terminal/shell end run the following command: 
ELMERGRID 8 2 'fname'  -autoclean -out 'path' 
with 'fname' and 'path' replaced by the information from the error message. 
Additionally, you should check that 'ELMERGRID' when entered in the terminal results in a correct call to the ElmerGrid-program. If that fails already, then your system just does not know about your Elmer-installation.

**Comment by HoWilgh** [comment]
Works now without the above error... with and without the line.
The .unv is created.

I get now "SMESH: Elmer executable not found. Check system variables."
But ElmerGrid can be started in a terminal from everywhere on my system.

What is the expected behaviour? I do neither get a string in the Salome-python-console, nor a extra window showing the requested path and filename information.

THX,
HoWil

**Comment by physici** [comment]
The current error message tells us that Salome is not able to find your Elmer binaries. That is why you do not see the other error again. However, they are known to the system when called from the terminal. That is very strange.

For verification:
Could you start Salome and then enter the following lines into the Python input window (usually at the bottom of the interface).
`from distutils import spawn`
`spawn.find_executable('elmergrid')`

These commands should result in the path of the elmergrid binary. If it returns nothing then the binaries are not linked like they are supposed to be. Additionally, could you check in the environment variables whether there is one pointing to the /bin-directory of your Elmer-installation?

Unfortunately, I am not using Linux. So it is unknown territory. But I will ask around, if someone can shine some light on this issue.

**Comment by HoWilgh** [comment]
First of all, I could not test your lines of code yet but I will for sure do it. 
I am asking myself if it simply is related to case sensitivity in linux terminal. 
I looked into  salome_plugins.py and found 
subprocess.Popen("ELMERGRID 8 2 {0} -autoclean -out {1}".format(fname, path))

Above you suggest to search for 'elmergrid' and on linux ElmerGrid is started with "ElmerGrid". 
Maybe spawn.find_executable already takes care about that, I don't know. 

BR 
Howil

**Comment by physici** [comment]
You might be on the right track. On Windows I do not have to think about upper and lower case on the terminal. That is why I have told you different variants of 'ElmerGrid'. 
A colleague confirmed that Linux is strictly case sensitive. Only the call to 'ElmerGrid' will result in the correct functionality. I have changed that. Could you try it again? I do not have a Linux system for testing :-\

**Comment by HoWilgh** [comment]
Finally the export is working!

I first got an error as it can be seen here...
![screenshot from 2017-03-31 21-26-01](https://cloud.githubusercontent.com/assets/9978035/24567033/36654e9c-165c-11e7-897e-cd86c7bc7e70.jpg)

But after changing Line 304 in salome_plugins.py from
`                    subprocess.Popen("ElmerGrid 8 2 {0} -autoclean -out {1}".format(fname, path))`
to
`                    subprocess.Popen("ElmerGrid 8 2 {0} -autoclean -out {1}".format(fname, path) , shell=True)`
it worked.

Please see also 
http://stackoverflow.com/questions/18962785/oserror-errno-2-no-such-file-or-directory-while-using-python-subprocess-in-dj#18962815

The .unv is with the above exported without error and processed with Elmergrid.

BR,
HoWil

**Comment by physici** [comment]
Thanks for the input!! I will change the code according to your suggestion.
